import { DamageFalloff, FireMode, type WeaponDefinition, type WeaponId } from '../types/weapons';

const DEG = Math.PI / 180;

/**
 * Every weapon in the game is a row in this table. Adding a weapon requires no
 * code changes anywhere else: the server validates against these numbers and
 * the client builds its view model and audio from the same record.
 */
export const WEAPON_DEFINITIONS: Record<WeaponId, WeaponDefinition> = {
  pistol: {
    id: 'pistol',
    name: 'Desert Eagle',
    slot: 1,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 280,
    damage: 42,
    pellets: 1,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadMs: 1500,
    reloadEmptyMs: 1850,
    range: 95,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.55,
    falloffStart: 22,
    projectileSpeed: 0,
    impactImpulse: 5.2,
    headMultiplier: 4.2,
    chestMultiplier: 1.35,
    bodyMultiplier: 1,
    limbMultiplier: 0.45,
    moveSpeedMultiplier: 1.0,
    aimMoveSpeedMultiplier: 0.62,
    aimFovMultiplier: 0.82,
    aimTimeMs: 140,
    equipMs: 340,
    recoil: {
      vertical: 1.45 * DEG,
      horizontal: 0.55 * DEG,
      recovery: 7.5,
      cameraPunch: 0.78,
      viewKick: 0.038,
    },
    spread: {
      base: 0.4 * DEG,
      perShot: 0.72 * DEG,
      max: 5.2 * DEG,
      recovery: 6.5 * DEG,
      moveMultiplier: 2.1,
      airMultiplier: 3.0,
      aimMultiplier: 0.42,
      crouchMultiplier: 0.75,
    },
    audio: { fire: 'pistol', reload: 'pistol_reload', pitch: 0.92, maxDistance: 100 },
    visual: {
      color: 0x2a2d33,
      accentColor: 0xb8a060,
      size: [0.1, 0.17, 0.32],
      muzzleFlashScale: 0.95,
      tracerWidth: 0.022,
      tracerColor: 0xffd48a,
      shellEjection: true,
      // Camera-local: +X right, +Y up, -Z forward. Barrel must leave the FOV.
      hipPosition: [0.21, -0.22, -0.42],
      aimPosition: [0.0, -0.12, -0.32],
    },
  },

  smg: {
    id: 'smg',
    name: 'VX-4 Ripper',
    slot: 2,
    fireMode: FireMode.Auto,
    burstCount: 1,
    rpm: 900,
    damage: 18,
    pellets: 1,
    magazineSize: 32,
    reserveAmmo: 160,
    reloadMs: 1750,
    reloadEmptyMs: 2100,
    range: 70,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.42,
    falloffStart: 14,
    projectileSpeed: 0,
    impactImpulse: 2.8,
    headMultiplier: 6.2,
    chestMultiplier: 1.22,
    bodyMultiplier: 1,
    limbMultiplier: 0.4,
    moveSpeedMultiplier: 0.97,
    aimMoveSpeedMultiplier: 0.6,
    aimFovMultiplier: 0.85,
    aimTimeMs: 150,
    equipMs: 380,
    recoil: {
      vertical: 0.55 * DEG,
      horizontal: 0.42 * DEG,
      recovery: 11,
      cameraPunch: 0.32,
      viewKick: 0.018,
    },
    spread: {
      base: 0.6 * DEG,
      perShot: 0.34 * DEG,
      max: 6.5 * DEG,
      recovery: 9 * DEG,
      moveMultiplier: 1.7,
      airMultiplier: 2.6,
      aimMultiplier: 0.55,
      crouchMultiplier: 0.8,
    },
    audio: { fire: 'smg', reload: 'reload_light', pitch: 1.18, maxDistance: 100 },
    visual: {
      color: 0x24272c,
      accentColor: 0xff7a3d,
      size: [0.11, 0.19, 0.48],
      muzzleFlashScale: 0.8,
      tracerWidth: 0.016,
      tracerColor: 0xffc46a,
      shellEjection: true,
      hipPosition: [0.2, -0.2, -0.46],
      aimPosition: [0.0, -0.125, -0.34],
    },
  },

  rifle: {
    id: 'rifle',
    name: 'M4A1 Carbine',
    slot: 3,
    fireMode: FireMode.Auto,
    burstCount: 1,
    rpm: 640,
    damage: 27,
    pellets: 1,
    magazineSize: 30,
    reserveAmmo: 150,
    reloadMs: 2050,
    reloadEmptyMs: 2500,
    range: 140,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.68,
    falloffStart: 40,
    projectileSpeed: 0,
    impactImpulse: 4.5,
    headMultiplier: 4.1,
    chestMultiplier: 1.45,
    bodyMultiplier: 1,
    limbMultiplier: 0.5,
    moveSpeedMultiplier: 0.94,
    aimMoveSpeedMultiplier: 0.55,
    aimFovMultiplier: 0.7,
    aimTimeMs: 190,
    equipMs: 450,
    recoil: {
      vertical: 0.78 * DEG,
      horizontal: 0.3 * DEG,
      recovery: 8.5,
      cameraPunch: 0.45,
      viewKick: 0.024,
    },
    spread: {
      base: 0.28 * DEG,
      perShot: 0.4 * DEG,
      max: 5.5 * DEG,
      recovery: 7.5 * DEG,
      moveMultiplier: 2.4,
      airMultiplier: 3.4,
      aimMultiplier: 0.35,
      crouchMultiplier: 0.7,
    },
    audio: { fire: 'rifle', reload: 'reload_heavy', pitch: 1.0, maxDistance: 150 },
    visual: {
      color: 0x1c1e22,
      accentColor: 0x3a3f46,
      size: [0.1, 0.2, 0.72],
      muzzleFlashScale: 2.85,
      tracerWidth: 0.026,
      tracerColor: 0xfff0c0,
      shellEjection: true,
      hipPosition: [0.2, -0.19, -0.48],
      aimPosition: [0.0, -0.1, -0.34],
    },
  },

  shotgun: {
    id: 'shotgun',
    name: 'BR-12 Breaker',
    slot: 4,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 78,
    damage: 13,
    pellets: 9,
    magazineSize: 6,
    reserveAmmo: 36,
    reloadMs: 2600,
    reloadEmptyMs: 3200,
    range: 42,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.18,
    falloffStart: 7,
    projectileSpeed: 0,
    impactImpulse: 9,
    headMultiplier: 8,
    chestMultiplier: 1.15,
    bodyMultiplier: 1,
    limbMultiplier: 0.5,
    moveSpeedMultiplier: 0.92,
    aimMoveSpeedMultiplier: 0.55,
    aimFovMultiplier: 0.9,
    aimTimeMs: 220,
    equipMs: 520,
    recoil: {
      vertical: 3.4 * DEG,
      horizontal: 0.7 * DEG,
      recovery: 6,
      cameraPunch: 1.6,
      viewKick: 0.07,
    },
    spread: {
      base: 3.6 * DEG,
      perShot: 0.5 * DEG,
      max: 6.5 * DEG,
      recovery: 6 * DEG,
      moveMultiplier: 1.25,
      airMultiplier: 1.5,
      aimMultiplier: 0.72,
      crouchMultiplier: 0.9,
    },
    audio: { fire: 'shotgun', reload: 'reload_shell', pitch: 1.0, maxDistance: 160 },
    visual: {
      color: 0x3a2a1e,
      accentColor: 0x9a6b3f,
      size: [0.11, 0.19, 0.7],
      muzzleFlashScale: 1.5,
      tracerWidth: 0.014,
      tracerColor: 0xffb066,
      shellEjection: true,
      hipPosition: [0.22, -0.2, -0.58],
      aimPosition: [0.0, -0.12, -0.42],
    },
  },

  sniper: {
    id: 'sniper',
    name: 'LR-88 Verdict',
    slot: 5,
    fireMode: FireMode.BoltAction,
    burstCount: 1,
    rpm: 48,
    damage: 92,
    pellets: 1,
    magazineSize: 5,
    reserveAmmo: 25,
    reloadMs: 3000,
    reloadEmptyMs: 3400,
    range: 300,
    falloff: DamageFalloff.None,
    falloffMinMultiplier: 1,
    falloffStart: 300,
    projectileSpeed: 0,
    impactImpulse: 14,
    headMultiplier: 2.2,
    chestMultiplier: 1.15,
    bodyMultiplier: 1,
    limbMultiplier: 0.55,
    moveSpeedMultiplier: 0.88,
    aimMoveSpeedMultiplier: 0.4,
    aimFovMultiplier: 0.28,
    aimTimeMs: 300,
    scoped: true,
    equipMs: 620,
    recoil: {
      vertical: 4.2 * DEG,
      horizontal: 0.5 * DEG,
      recovery: 5,
      cameraPunch: 2.2,
      viewKick: 0.09,
    },
    spread: {
      base: 0.05 * DEG,
      perShot: 2.5 * DEG,
      max: 8 * DEG,
      recovery: 5 * DEG,
      moveMultiplier: 12,
      airMultiplier: 20,
      aimMultiplier: 0.02,
      crouchMultiplier: 0.5,
    },
    audio: { fire: 'sniper', reload: 'reload_heavy', pitch: 1.0, maxDistance: 260 },
    visual: {
      color: 0x1a1d21,
      accentColor: 0x2f6f4f,
      size: [0.09, 0.16, 0.9],
      muzzleFlashScale: 1.3,
      tracerWidth: 0.024,
      tracerColor: 0xbfe6ff,
      shellEjection: true,
      hipPosition: [0.23, -0.19, -0.62],
      aimPosition: [0.0, -0.1, -0.3],
    },
  },

  glock: {
    id: 'glock',
    name: 'Glock 17',
    slot: 1,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 400,
    damage: 24,
    pellets: 1,
    magazineSize: 17,
    reserveAmmo: 85,
    reloadMs: 1250,
    reloadEmptyMs: 1550,
    range: 85,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.5,
    falloffStart: 20,
    projectileSpeed: 0,
    impactImpulse: 3.2,
    headMultiplier: 4.4,
    chestMultiplier: 1.3,
    bodyMultiplier: 1,
    limbMultiplier: 0.45,
    moveSpeedMultiplier: 1.0,
    aimMoveSpeedMultiplier: 0.64,
    aimFovMultiplier: 0.8,
    aimTimeMs: 145,
    equipMs: 340,
    recoil: {
      vertical: 0.68 * DEG,
      horizontal: 0.2 * DEG,
      recovery: 12,
      cameraPunch: 0.34,
      viewKick: 0.016,
    },
    spread: {
      base: 0.32 * DEG,
      perShot: 0.48 * DEG,
      max: 4.2 * DEG,
      recovery: 7.5 * DEG,
      moveMultiplier: 2.0,
      airMultiplier: 2.8,
      aimMultiplier: 0.42,
      crouchMultiplier: 0.72,
    },
    audio: { fire: 'pistol', reload: 'pistol_reload', pitch: 1.02, maxDistance: 90 },
    visual: {
      color: 0x1c1e22,
      accentColor: 0x8a9099,
      size: [0.1, 0.16, 0.3],
      muzzleFlashScale: 0.65,
      tracerWidth: 0.016,
      tracerColor: 0xffd48a,
      shellEjection: true,
      hipPosition: [0.19, -0.24, -0.38],
      aimPosition: [0.0, -0.118, -0.3],
    },
  },

  magnum: {
    id: 'magnum',
    name: 'DX-50 Hammer',
    slot: 1,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 165,
    damage: 52,
    pellets: 1,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadMs: 1550,
    reloadEmptyMs: 1900,
    range: 110,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.62,
    falloffStart: 28,
    projectileSpeed: 0,
    impactImpulse: 7.5,
    headMultiplier: 3.6,
    chestMultiplier: 1.4,
    bodyMultiplier: 1,
    limbMultiplier: 0.5,
    moveSpeedMultiplier: 0.96,
    aimMoveSpeedMultiplier: 0.52,
    aimFovMultiplier: 0.76,
    aimTimeMs: 170,
    equipMs: 420,
    recoil: {
      vertical: 2.1 * DEG,
      horizontal: 0.55 * DEG,
      recovery: 6.5,
      cameraPunch: 1.15,
      viewKick: 0.048,
    },
    spread: {
      base: 0.42 * DEG,
      perShot: 1.1 * DEG,
      max: 5.5 * DEG,
      recovery: 5.5 * DEG,
      moveMultiplier: 2.4,
      airMultiplier: 3.2,
      aimMultiplier: 0.38,
      crouchMultiplier: 0.7,
    },
    audio: { fire: 'magnum', reload: 'reload_heavy', pitch: 1.0, maxDistance: 130 },
    visual: {
      color: 0x161412,
      accentColor: 0xd4a44a,
      size: [0.12, 0.2, 0.38],
      muzzleFlashScale: 1.15,
      tracerWidth: 0.028,
      tracerColor: 0xffc46a,
      shellEjection: true,
      hipPosition: [0.2, -0.22, -0.4],
      aimPosition: [0.0, -0.11, -0.32],
    },
  },

  usp: {
    id: 'usp',
    name: 'USP Compact',
    slot: 1,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 360,
    damage: 28,
    pellets: 1,
    magazineSize: 12,
    reserveAmmo: 60,
    reloadMs: 1350,
    reloadEmptyMs: 1650,
    range: 90,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.52,
    falloffStart: 22,
    projectileSpeed: 0,
    impactImpulse: 3.6,
    headMultiplier: 4.3,
    chestMultiplier: 1.32,
    bodyMultiplier: 1,
    limbMultiplier: 0.45,
    moveSpeedMultiplier: 1.0,
    aimMoveSpeedMultiplier: 0.64,
    aimFovMultiplier: 0.8,
    aimTimeMs: 140,
    equipMs: 320,
    recoil: {
      vertical: 0.72 * DEG,
      horizontal: 0.22 * DEG,
      recovery: 11,
      cameraPunch: 0.38,
      viewKick: 0.018,
    },
    spread: {
      base: 0.3 * DEG,
      perShot: 0.5 * DEG,
      max: 4.0 * DEG,
      recovery: 7.8 * DEG,
      moveMultiplier: 1.9,
      airMultiplier: 2.7,
      aimMultiplier: 0.4,
      crouchMultiplier: 0.72,
    },
    audio: { fire: 'usp', reload: 'pistol_reload', pitch: 1.0, maxDistance: 95 },
    visual: {
      color: 0x22262c,
      accentColor: 0x6a90b8,
      size: [0.09, 0.15, 0.28],
      muzzleFlashScale: 0.7,
      tracerWidth: 0.017,
      tracerColor: 0xd8e8ff,
      shellEjection: true,
      hipPosition: [0.19, -0.24, -0.38],
      aimPosition: [0.0, -0.118, -0.3],
    },
  },

  makarov: {
    id: 'makarov',
    name: 'Makarov PM',
    slot: 1,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 320,
    damage: 26,
    pellets: 1,
    magazineSize: 8,
    reserveAmmo: 48,
    reloadMs: 1200,
    reloadEmptyMs: 1480,
    range: 75,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.48,
    falloffStart: 16,
    projectileSpeed: 0,
    impactImpulse: 3.0,
    headMultiplier: 4.5,
    chestMultiplier: 1.28,
    bodyMultiplier: 1,
    limbMultiplier: 0.45,
    moveSpeedMultiplier: 1.0,
    aimMoveSpeedMultiplier: 0.66,
    aimFovMultiplier: 0.82,
    aimTimeMs: 130,
    equipMs: 300,
    recoil: {
      vertical: 0.62 * DEG,
      horizontal: 0.18 * DEG,
      recovery: 13,
      cameraPunch: 0.3,
      viewKick: 0.014,
    },
    spread: {
      base: 0.35 * DEG,
      perShot: 0.42 * DEG,
      max: 3.8 * DEG,
      recovery: 8.2 * DEG,
      moveMultiplier: 1.8,
      airMultiplier: 2.5,
      aimMultiplier: 0.44,
      crouchMultiplier: 0.74,
    },
    audio: { fire: 'usp', reload: 'pistol_reload', pitch: 1.12, maxDistance: 85 },
    visual: {
      color: 0x2a2e32,
      accentColor: 0xa8b0b8,
      size: [0.09, 0.14, 0.26],
      muzzleFlashScale: 0.58,
      tracerWidth: 0.015,
      tracerColor: 0xffe0a8,
      shellEjection: true,
      hipPosition: [0.18, -0.24, -0.36],
      aimPosition: [0.0, -0.12, -0.28],
    },
  },

  pdw: {
    id: 'pdw',
    name: 'Vector PDW',
    slot: 2,
    fireMode: FireMode.Auto,
    burstCount: 1,
    rpm: 1050,
    damage: 16,
    pellets: 1,
    magazineSize: 25,
    reserveAmmo: 150,
    reloadMs: 1600,
    reloadEmptyMs: 1950,
    range: 65,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.38,
    falloffStart: 12,
    projectileSpeed: 0,
    impactImpulse: 2.4,
    headMultiplier: 5.8,
    chestMultiplier: 1.2,
    bodyMultiplier: 1,
    limbMultiplier: 0.4,
    moveSpeedMultiplier: 0.99,
    aimMoveSpeedMultiplier: 0.62,
    aimFovMultiplier: 0.86,
    aimTimeMs: 130,
    equipMs: 340,
    recoil: {
      vertical: 0.42 * DEG,
      horizontal: 0.38 * DEG,
      recovery: 13,
      cameraPunch: 0.26,
      viewKick: 0.014,
    },
    spread: {
      base: 0.55 * DEG,
      perShot: 0.28 * DEG,
      max: 5.8 * DEG,
      recovery: 10 * DEG,
      moveMultiplier: 1.5,
      airMultiplier: 2.3,
      aimMultiplier: 0.5,
      crouchMultiplier: 0.78,
    },
    audio: { fire: 'smg', reload: 'reload_light', pitch: 1.28, maxDistance: 95 },
    visual: {
      color: 0x1e2228,
      accentColor: 0x4ec4ff,
      size: [0.1, 0.17, 0.42],
      muzzleFlashScale: 0.72,
      tracerWidth: 0.014,
      tracerColor: 0xa8e0ff,
      shellEjection: true,
      hipPosition: [0.2, -0.2, -0.44],
      aimPosition: [0.0, -0.125, -0.33],
    },
  },

  bizon: {
    id: 'bizon',
    name: 'PP-19 Bizon',
    slot: 2,
    fireMode: FireMode.Auto,
    burstCount: 1,
    rpm: 680,
    damage: 20,
    pellets: 1,
    magazineSize: 64,
    reserveAmmo: 192,
    reloadMs: 2100,
    reloadEmptyMs: 2500,
    range: 75,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.45,
    falloffStart: 16,
    projectileSpeed: 0,
    impactImpulse: 3.0,
    headMultiplier: 5.5,
    chestMultiplier: 1.25,
    bodyMultiplier: 1,
    limbMultiplier: 0.42,
    moveSpeedMultiplier: 0.96,
    aimMoveSpeedMultiplier: 0.58,
    aimFovMultiplier: 0.84,
    aimTimeMs: 155,
    equipMs: 400,
    recoil: {
      vertical: 0.5 * DEG,
      horizontal: 0.36 * DEG,
      recovery: 10,
      cameraPunch: 0.3,
      viewKick: 0.016,
    },
    spread: {
      base: 0.5 * DEG,
      perShot: 0.3 * DEG,
      max: 5.5 * DEG,
      recovery: 8.5 * DEG,
      moveMultiplier: 1.65,
      airMultiplier: 2.5,
      aimMultiplier: 0.52,
      crouchMultiplier: 0.78,
    },
    audio: { fire: 'smg', reload: 'reload_heavy', pitch: 0.88, maxDistance: 105 },
    visual: {
      color: 0x2a3228,
      accentColor: 0x8a9a6a,
      size: [0.11, 0.2, 0.5],
      muzzleFlashScale: 0.85,
      tracerWidth: 0.016,
      tracerColor: 0xd8e8a8,
      shellEjection: true,
      hipPosition: [0.2, -0.2, -0.46],
      aimPosition: [0.0, -0.122, -0.34],
    },
  },

  assault: {
    id: 'assault',
    name: 'AR-C Assault',
    slot: 3,
    fireMode: FireMode.Auto,
    burstCount: 1,
    rpm: 720,
    damage: 24,
    pellets: 1,
    magazineSize: 30,
    reserveAmmo: 150,
    reloadMs: 1950,
    reloadEmptyMs: 2350,
    range: 130,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.62,
    falloffStart: 35,
    projectileSpeed: 0,
    impactImpulse: 4.2,
    headMultiplier: 4.0,
    chestMultiplier: 1.4,
    bodyMultiplier: 1,
    limbMultiplier: 0.48,
    moveSpeedMultiplier: 0.95,
    aimMoveSpeedMultiplier: 0.56,
    aimFovMultiplier: 0.72,
    aimTimeMs: 175,
    equipMs: 430,
    recoil: {
      vertical: 0.7 * DEG,
      horizontal: 0.28 * DEG,
      recovery: 9,
      cameraPunch: 0.4,
      viewKick: 0.022,
    },
    spread: {
      base: 0.3 * DEG,
      perShot: 0.36 * DEG,
      max: 5.2 * DEG,
      recovery: 8 * DEG,
      moveMultiplier: 2.2,
      airMultiplier: 3.2,
      aimMultiplier: 0.36,
      crouchMultiplier: 0.7,
    },
    audio: { fire: 'assault', reload: 'reload_heavy', pitch: 1.05, maxDistance: 145 },
    visual: {
      color: 0x1a1c20,
      accentColor: 0x5a8a4a,
      size: [0.1, 0.2, 0.7],
      muzzleFlashScale: 1.05,
      tracerWidth: 0.024,
      tracerColor: 0xffe8a0,
      shellEjection: true,
      hipPosition: [0.2, -0.19, -0.48],
      aimPosition: [0.0, -0.1, -0.34],
    },
  },

  ak: {
    id: 'ak',
    name: 'AK-74',
    slot: 3,
    fireMode: FireMode.Auto,
    burstCount: 1,
    rpm: 600,
    damage: 30,
    pellets: 1,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadMs: 2200,
    reloadEmptyMs: 2650,
    range: 135,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.7,
    falloffStart: 38,
    projectileSpeed: 0,
    impactImpulse: 5.2,
    headMultiplier: 3.9,
    chestMultiplier: 1.5,
    bodyMultiplier: 1,
    limbMultiplier: 0.52,
    moveSpeedMultiplier: 0.93,
    aimMoveSpeedMultiplier: 0.52,
    aimFovMultiplier: 0.68,
    aimTimeMs: 185,
    equipMs: 470,
    recoil: {
      vertical: 0.95 * DEG,
      horizontal: 0.4 * DEG,
      recovery: 7.5,
      cameraPunch: 0.55,
      viewKick: 0.028,
    },
    spread: {
      base: 0.34 * DEG,
      perShot: 0.46 * DEG,
      max: 6.0 * DEG,
      recovery: 7 * DEG,
      moveMultiplier: 2.5,
      airMultiplier: 3.5,
      aimMultiplier: 0.38,
      crouchMultiplier: 0.68,
    },
    audio: { fire: 'assault', reload: 'reload_heavy', pitch: 0.9, maxDistance: 155 },
    visual: {
      color: 0x2a241c,
      accentColor: 0xb8863a,
      size: [0.11, 0.21, 0.74],
      muzzleFlashScale: 1.2,
      tracerWidth: 0.027,
      tracerColor: 0xffc878,
      shellEjection: true,
      hipPosition: [0.21, -0.19, -0.5],
      aimPosition: [0.0, -0.1, -0.35],
    },
  },

  autosg: {
    id: 'autosg',
    name: 'AA-12 Storm',
    slot: 4,
    fireMode: FireMode.Auto,
    burstCount: 1,
    rpm: 220,
    damage: 10,
    pellets: 8,
    magazineSize: 8,
    reserveAmmo: 40,
    reloadMs: 2800,
    reloadEmptyMs: 3300,
    range: 38,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.15,
    falloffStart: 6,
    projectileSpeed: 0,
    impactImpulse: 8,
    headMultiplier: 7,
    chestMultiplier: 1.12,
    bodyMultiplier: 1,
    limbMultiplier: 0.5,
    moveSpeedMultiplier: 0.9,
    aimMoveSpeedMultiplier: 0.52,
    aimFovMultiplier: 0.88,
    aimTimeMs: 210,
    equipMs: 540,
    recoil: {
      vertical: 2.6 * DEG,
      horizontal: 0.9 * DEG,
      recovery: 7,
      cameraPunch: 1.2,
      viewKick: 0.055,
    },
    spread: {
      base: 3.8 * DEG,
      perShot: 0.6 * DEG,
      max: 7.0 * DEG,
      recovery: 5.5 * DEG,
      moveMultiplier: 1.3,
      airMultiplier: 1.6,
      aimMultiplier: 0.75,
      crouchMultiplier: 0.88,
    },
    audio: { fire: 'autosg', reload: 'reload_shell', pitch: 1.05, maxDistance: 150 },
    visual: {
      color: 0x2c3036,
      accentColor: 0xe05040,
      size: [0.12, 0.2, 0.68],
      muzzleFlashScale: 1.55,
      tracerWidth: 0.015,
      tracerColor: 0xff8866,
      shellEjection: true,
      hipPosition: [0.22, -0.2, -0.56],
      aimPosition: [0.0, -0.12, -0.4],
    },
  },

  saiga: {
    id: 'saiga',
    name: 'Saiga-12',
    slot: 4,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 140,
    damage: 12,
    pellets: 8,
    magazineSize: 5,
    reserveAmmo: 30,
    reloadMs: 2400,
    reloadEmptyMs: 2900,
    range: 40,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.2,
    falloffStart: 7,
    projectileSpeed: 0,
    impactImpulse: 8.5,
    headMultiplier: 7.5,
    chestMultiplier: 1.15,
    bodyMultiplier: 1,
    limbMultiplier: 0.5,
    moveSpeedMultiplier: 0.91,
    aimMoveSpeedMultiplier: 0.54,
    aimFovMultiplier: 0.88,
    aimTimeMs: 200,
    equipMs: 500,
    recoil: {
      vertical: 3.0 * DEG,
      horizontal: 0.75 * DEG,
      recovery: 6.5,
      cameraPunch: 1.4,
      viewKick: 0.06,
    },
    spread: {
      base: 3.4 * DEG,
      perShot: 0.55 * DEG,
      max: 6.2 * DEG,
      recovery: 6 * DEG,
      moveMultiplier: 1.28,
      airMultiplier: 1.55,
      aimMultiplier: 0.7,
      crouchMultiplier: 0.88,
    },
    audio: { fire: 'autosg', reload: 'reload_shell', pitch: 0.92, maxDistance: 155 },
    visual: {
      color: 0x3a3228,
      accentColor: 0xc07030,
      size: [0.11, 0.19, 0.66],
      muzzleFlashScale: 1.4,
      tracerWidth: 0.014,
      tracerColor: 0xffa060,
      shellEjection: true,
      hipPosition: [0.22, -0.2, -0.55],
      aimPosition: [0.0, -0.12, -0.4],
    },
  },

  dmr: {
    id: 'dmr',
    name: 'M1A Scout',
    slot: 5,
    fireMode: FireMode.Single,
    burstCount: 1,
    rpm: 180,
    damage: 55,
    pellets: 1,
    magazineSize: 10,
    reserveAmmo: 40,
    reloadMs: 2400,
    reloadEmptyMs: 2800,
    range: 220,
    falloff: DamageFalloff.Linear,
    falloffMinMultiplier: 0.75,
    falloffStart: 80,
    projectileSpeed: 0,
    impactImpulse: 9,
    headMultiplier: 2.8,
    chestMultiplier: 1.35,
    bodyMultiplier: 1,
    limbMultiplier: 0.55,
    moveSpeedMultiplier: 0.9,
    aimMoveSpeedMultiplier: 0.45,
    aimFovMultiplier: 0.42,
    aimTimeMs: 240,
    scoped: true,
    equipMs: 560,
    recoil: {
      vertical: 2.4 * DEG,
      horizontal: 0.4 * DEG,
      recovery: 6,
      cameraPunch: 1.3,
      viewKick: 0.05,
    },
    spread: {
      base: 0.12 * DEG,
      perShot: 1.4 * DEG,
      max: 6 * DEG,
      recovery: 5.5 * DEG,
      moveMultiplier: 6,
      airMultiplier: 10,
      aimMultiplier: 0.08,
      crouchMultiplier: 0.55,
    },
    audio: { fire: 'sniper', reload: 'reload_heavy', pitch: 1.12, maxDistance: 200 },
    visual: {
      color: 0x1c2220,
      accentColor: 0x4a8a6a,
      size: [0.1, 0.18, 0.85],
      muzzleFlashScale: 1.15,
      tracerWidth: 0.022,
      tracerColor: 0xc0ffd8,
      shellEjection: true,
      hipPosition: [0.22, -0.19, -0.58],
      aimPosition: [0.0, -0.1, -0.32],
    },
  },
};

export const WEAPON_IDS: WeaponId[] = Object.keys(WEAPON_DEFINITIONS);

/** The loadout every player spawns with, in slot order. */
export const DEFAULT_LOADOUT: WeaponId[] = ['pistol', 'smg', 'rifle', 'shotgun', 'sniper'];

export function getWeapon(id: WeaponId): WeaponDefinition {
  const def = WEAPON_DEFINITIONS[id];
  if (!def) throw new Error(`Unknown weapon id: ${id}`);
  return def;
}

export function isWeaponId(id: unknown): id is WeaponId {
  return typeof id === 'string' && Object.prototype.hasOwnProperty.call(WEAPON_DEFINITIONS, id);
}

/**
 * Weapons are sent in snapshots as a single byte. The index is derived from the
 * definition order so it stays stable as long as the table order is stable.
 */
export const WEAPON_INDEX: Record<WeaponId, number> = Object.fromEntries(
  WEAPON_IDS.map((id, i) => [id, i]),
);
export const WEAPON_BY_INDEX: WeaponId[] = WEAPON_IDS.slice();

export function weaponIndex(id: WeaponId): number {
  return WEAPON_INDEX[id] ?? 0;
}

export function weaponFromIndex(index: number): WeaponId {
  return WEAPON_BY_INDEX[index] ?? WEAPON_BY_INDEX[0]!;
}
